# Generated by Django 2.1 on 2018-08-21 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktype',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='risktype',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
